### ISSUE TITLE
Dart-sass

### ISSUE THREAD

**Issue by john681611** [yibn2008/fast-sass-loader#34]
It's being discussed in sass-loader wondering if it's been considered here as ruby-sass is being deprecated soon.
https://github.com/webpack-contrib/sass-loader/issues/435

**Comment by yibn2008** [comment]
I think node-sass is fast enough and dart-sass is still under heavily development, so the answer is NO.

**Comment by stephanemagnenat** [comment]
One reason to allow dart-sass could be that it is supposedly [properly supports CSS media query Level 4 syntax](https://github.com/sass/libsass/issues/2698#issuecomment-448567942), which currently libsass does not. But I agree that the best would be to implement the feature in libsass.

**Comment by ArcanisCz** [comment]
I second dart-sass option. Our main issue with node-sass is the binary nature of its dependencies, which are not practical in our enviroments.

**Comment by ngryman** [comment]
@yibn2008 Any second though about this?

`dart-sass` is pretty stable now and is a perfectly valid replacement for `node-sass` in late 2019. 

`node-sass` is native and brings operational limitations compared to a full JavaScript solution:
* It needs a whole toolchain to compile, which in our case, clutters our Docker images.
* It results in slower install times because of the build step.
* It limits dependencies portability and make it more difficult to cache dependencies across several platforms (we need to recompile `node-sass` specifically).
* It's tied to the Node ABI which is another portable limitation with the latests change of N-API

**Comment by johncrim** [comment]
In addition, dart-sass is currently the only sass implementation including [the new module system](https://github.com/sass/sass/blob/master/accepted/module-system.md), which is a huge advance in sass. The sass project also states that dart-sass is the recommended and go-forward implementation. Right now one can use sass modules (`@use`) in Angular 9 apps using the regular sass-loader.

**Comment by yibn2008** [comment]
@ngryman  I don't have any experience with dart-sass, but if you really want this feature support, please provider a PR, I'll

**Comment by ngryman** [comment]
@yibn2008 Awesome, thanks for reconsidering! I'll open a PR based on my fork early January.

**Comment by ngryman** [comment]
^ For those interested I just opened a PR for that.

**Comment by xmsz** [comment]
any updated?

**Comment by tay1orjones** [comment]
LibSass is now [officially deprecated](https://sass-lang.com/blog/libsass-is-deprecated)

**Comment by chrisgbaker** [comment]
Has there been any discussion of using [sass/embedded-host-node](https://github.com/sass/embedded-host-node) over `sass` directly, given the poor performance of dart-sass as an npm package?

**Comment by yibn2008** [comment]
already supported dart-sass
