### ISSUE TITLE
Glob importer

### ISSUE THREAD

**Issue by opr** [yibn2008/fast-sass-loader#57]
Hello,

In my sass file I have 

`@import helpers/*`

how can I make this work with fast-sass-loader?

Thanks

**Comment by yibn2008** [comment]
Is this syntax legal in sass ?

**Comment by ollycross** [comment]
It is not in pure sass, but you can use [node-sass-glob-importer](https://www.npmjs.com/package/node-sass-glob-importer) with `sass-loader` in order to allow it:

```
// webpack.config.js
const globImporter = require('node-sass-glob-importer');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
 
module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract([
          {
            loader: 'css-loader'
          }, {
            loader: 'sass-loader',
            options: {
              importer: globImporter()
            }
          }
        ])
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin({
      filename: 'style.css'
    })
  ]
}
```

I'm running into trouble with a slow webpack build and have identified `sass-loader` as the culprit.  I'd like to try `fast-sass-loader` to see if it can help but the project in question makes use of glob importing to auto-import component files that may or may not be there.

**Comment by yibn2008** [comment]
no plan for this, close
